[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable form processing
[forms]
  # Enable form processing on all forms
  
[[forms]]
  name = "nieuwsbrief-inschrijving"
  
[functions]
  # Optional: you can add serverless functions here later